### ISSUE TITLE
Enhance Conversations archive page

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#13]
Instead of having the search only work dynamically within the conversations page, I'd like to create a dedicated search results page. This would clearly indicate "Search Results" and show the results on the map and the matching conversations below it.

This page would also be a destination for queries that originated from within conversations by users clicking on a keyword, place, or other link (?).

**Comment by codyml** [comment]
Update: we instead want to repurpose the current Conversations page to be a better search results page.  Current idea:
 - Featured Conversations will be moved to the Homepage
 - Make the All Conversations list and search field be the focus of the page
 - When a search is in progress, the map will grey out pins that aren't part of the search results
 - Start with 12 results instead of 6 for All Conversations
 - Order results by random, then once a search has been done order them by relevance
 - Add a keyword word cloud (merged from #32)

Next step: mock up what the updated page(s) would look like; not ready for dev yet.

**Comment by kcirerick** [comment]
<h1>
	Search Results Page Design Notes:
</h1>
<ul>
	<li>Once a search is in progress, all conversations returned by the search will appear red on the conversations map, all other conversations will be greyed-out.</li><br>
	<li><strong>Filter by</strong>: Allows the user to filter search results according to several options including:
			<ul>
				<li><strong>Location</strong>- Conversations will only show up on the results page if they contain both the search term and a matching location.</li>
				<li><strong>Grade Level/Age</strong>- Conversations will only show up on the results page if they contain both the search term and the matching grade level/age. </li>
				<li><strong>Text Field Options</strong>: Allows the user to specify which text fields are searched.
					<ul>
						<li>Title</li>
						<li>Text Fields</li>
						<li>Transcript</li>
						<li>Additional Info</li>
					</ul>
				</li>
			</ul>
	</li><br>
	<li><strong>Sort by</strong>: Sorts search results according to selected option. Ideas so far include:
		<ul>
			<li>Relevance</li>
			<li>Grade Level/Age</li>
			<li>Newest</li>
			<li>Oldest</li>
		</ul>
	</li><br>
	<li>Keywords will be made clickable from within a conversation, this can be implemented by turning rendered keywords in Conversation single into links to URLs to the Conversations search page with a search pre-filled for their respective keyword. To work, the Conversations search page must reflect current search state in URL.</li>
</ul>

**Comment by cartosattva** [comment]
A few follow up comments from our conversation yesterday...

**Search**
Could we allow people to do a spatial search that would return results within, say, 20 miles of a place name or coordinate?

**Map**
Can we zoom the map to the extent of all results?

**Word cloud**
This is a list of keywords arranged in frequency order. See attached mockup. Clicking a keyword should run a search, with exact keyword matches appearing at the top.

![word_cloud](https://user-images.githubusercontent.com/12202208/61984622-0a1d9700-afba-11e9-93c0-5a5f773e66ff.png)

**Filter by**
This option should be eliminated. We considered many options here and ultimately decided it wasn't a valuable feature. The only thing that seemed particularly useful was the grade level but then it would be very difficult to internationally standardize. So, let's eliminate it.

**Sort by:**
Initial state of of sort is random. A search updates sort to relevance.
"Most Popular" - can we just use the number of page visits?

**Conversation Cards**
See issue #59 : I'd like to reduce their size some and show at a minimum 12 on screen on initial load, if not more.

**Comment by codyml** [comment]
Hi!  Some responses/questions:

Spatial search shouldn't be a problem development-wise, but then wouldn't
we still need some kind of "Filter By" or an additional input field so
users can select how to search?

For the word cloud, were you thinking it would be the top 25 keywords or
so?  And, in our last conversation we decided that the keyword search would
just pre-fill the standard search box with the keyword and return results
by our standard "relevance" function, which we decided would weight results
in the following order:

   1. Title
   2. Keywords
   3. Narrative plain text fields
   4. Transcript
   5. Additional Info

Are we scratching that and instead allowing a second kind of filtering?  If
so, can you search for keywords and also use the main search box?  And, you
said that exact keyword matches appear at the top; will other, non-matches
also appear lower down?  Which ones?

For "Sort By," last time we decided on what you said first, that initial
state is random and after searching, it's sorted by relevance.  We can also
track each conversation's page view count and use it for sorting, but how
will that show up on the site?  Will we be using that instead of the
sorting by random for initial state?  Or do we want a UI control to allow
user control of sorting?

For changes to the map, I remembered that we were thinking about maybe
rewriting the map in Leaflet (#42) and changing a lot of how it works
during that process.  I think that's a great idea and I wonder if we should
put off having the pins not returned as search results change color to grey
and zooming into the returned pins until that set of changes?  From what I
remember, the Google Maps API isn't the easiest to work with compared to
Leaflet, though I'm sure we could figure out how to do those things it
might be worth holding off if we're going to be rewriting the map anyway.
But, up to you.

Finally, sounds good about changing the size of the conversation cards.

Let me know if you'd like to do a meeting to talk through any of this.
Once we finalize the feature specs I'm happy to make a mockup and start
dev, or I can work on other tasks we have – just let me know what you'd
like me to work on.

Thanks,
Cody

**Comment by cartosattva** [comment]
**Spatial Search**
How about two adjacent boxes: "Search by Place" and "Search by Keyword"??? The search by keyword wouldn't really mean keyword but would be full text search. Thoughts?

**Word Cloud**
Yes, say top 25 keywords. And yes, a keyword search would just use the standard relevance sorting as you describe. Sorry if I was unclear. I just meant that because it is unlikely that a keyword would appear in a title, exact keyword matches would be high relevance.

**Sorting**
I think there would be a UI element to choose sorting and it would include the following options: 

Relevance
Most Popular
Newest

Random would be an initial state if someone landed on the conversations page without a sorting method specified. Could we set the sorting method through the URL string?

**Map**
I like the idea of rewriting it in Leaflet so let's table these edits until then.

**Meeting**
We have our weekly meeting at 1:30 today - if you might be able to join that would be great.

erik

**Comment by codyml** [comment]
Ok, great, that all makes sense.  Sorry about not reading this message in
time for the meeting!  I wasn't working Monday.  To answer your questions:

   - Two boxes works me.  If we're doing a spatial search, we might also
   want to include adding a "searched location" marker or even a circle
   representing the searched radius in the map updates/leaflet rewrite issue
   (#42).
   - We can definitely set the sorting method through the URL string.

So, to sum everything up:

   - Move Featured Conversations to the homepage
   - Restructure UI so the list of conversation cards and filtering tools
   is the focus of the page
   - Update filtering tools:
      - 25 most popular keywords list; clicking one redirects to the same
      page with that keyword filled in in the "Search by Keyword" field
      - "Search by Place" text field that accepts either a place name or a
      coordinate set, geocodes it via Google Maps API and filters out results
      that are not within 20 miles of the geocoded coordinates
         - We could have a little drop-down that shows them geocoded
         results as they're typing and they can select one to auto-complete
         - "Search by Keyword" text field that performs a search by
      relevance (#12) and filters out results that aren't a match at
all; updates
      on keystroke (unless performance ends up being too bad)
      - UI element for controlling sorting with the following options:
         - Random (default if no search)
         - Relevance (default if searching, not an option if no search is
         performed)
         - Most Popular (descending page views; need to start tracking this)
         - Newest
      - Filter/sort state tied to URL; setting a filter/sort state then
      visiting that same URL again will preset same filter/sort state
   - Results use updated conversation card style (#59) and 12 load initially
   - Keywords on single conversation pages linked just like in the keyword
   cloud (#31)

Does that all sound right?  I'll get started on mocking this up, but let me
know if there's anything else.

**Comment by codyml** [comment]
Ok, great, that all makes sense.  Sorry about not reading this message in
time for the meeting!  I wasn't working Monday.  To answer your questions:

- Two boxes works me.  If we're doing a spatial search, we might also
   want to include adding a "searched location" marker or even a circle
   representing the searched radius in the map updates/leaflet rewrite issue
   (#42).
- We can definitely set the sorting method through the URL string.

So, to sum everything up:

- Move Featured Conversations to the homepage
- Restructure UI so the list of conversation cards and filtering tools
   is the focus of the page
- Update filtering tools:
  - 25 most popular keywords list; clicking one redirects to the same
      page with that keyword filled in in the "Search by Keyword" field
  - "Search by Place" text field that accepts either a place name or a
      coordinate set, geocodes it via Google Maps API and filters out results
      that are not within 20 miles of the geocoded coordinates
    - We could have a little drop-down that shows them geocoded
         results as they're typing and they can select one to auto-complete
  - "Search by Keyword" text field that performs a search by
      relevance (#12) and filters out results that aren't a match at
all; updates
      on keystroke (unless performance ends up being too bad)
  - UI element for controlling sorting with the following options:
    - Random (default if no search)
    - Relevance (default if searching, not an option if no search is
         performed)
    - Most Popular (descending page views; need to start tracking this)
    - Newest
  - Filter/sort state tied to URL; setting a filter/sort state then
      visiting that same URL again will preset same filter/sort state
- Results use updated conversation card style (#59) and 12 load initially
- Keywords on single conversation pages linked just like in the keyword
   cloud (#31)

Does that all sound right?  I'll get started on mocking this up, but let me
know if there's anything else.

**Comment by codyml** [comment]
Hi,

Thoughts on these designs?

   - This is the Homepage with Featured Conversations moved to it.
   <https://sketch.cloud/s/v1W2M/a/PknwzL>
   - This is Conversations with a thin banner map like on the homepage.
   <https://sketch.cloud/s/v1W2M/a/gdGkzq>
   - This is Conversations with the map and the search tools side-by-side.
   <https://sketch.cloud/s/v1W2M/a/8bOj2a>
   - This is Conversations with the map as a card alongside the
   conversations. <https://sketch.cloud/s/v1W2M/a/2nZqwJ>

As always, let me know if I missed something from our plan our if you'd
like to see something else.

Thanks,
Cody

**Comment by cartosattva** [comment]
Nice to see these coming together! Homepage looks good. On the conversations page, I prefer the "map on top" version. But so thin... I suppose it's a little wrapped up in the map redesign...e.g. it would be nice to expand the map area for a better spatial navigation experience. Also, we probably don't really need the page description at the top. The rest of the page looks quite nice. Even though it seems like a lot to have two different search boxes, I like how explicit it is (could we maybe eliminate or reduce the explanations?). Having a spatial search would be awesome, especially if it zooms to the right location?

**Comment by codyml** [comment]
Ok, here's the map on top one with no page description and a slightly
larger map <https://sketch.cloud/s/v1W2M/a/rampWA>.  That look good?  We
can definitely remove or reduce the explanations - want me to take them out
or do you know what you'd like them to say instead?  Zooming to the right
location would probably be better worked out in the map updates; do you
think it's okay to leave in for now if it doesn't zoom immediately?  We can
work on the map updates next and hopefully have those out sooner rather
than later!

If everything looks good, I can get started on implementing this!  I'll
update this issue with final specs and also move the other things we've
discussed into their respective issues.
